### ISSUE TITLE
tests!!!!

### ISSUE THREAD

**Issue by RachelEversmann** [R3C-hratx29/Hackfolio#147]

**Comment by rosswaycaster** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/9945807-128443003_5-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by rhiroy** [comment]
https://render.bitstrips.com/v2/cpanel/10221577-334918179_3-s1-v1.png?transparent=1&palette=1

**Comment by rhiroy** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10221577-334918179_3-s1-v1.png?transparent=1&palette=1&width=246)
